tasks:
  - name: setup
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
        FLASK_APP: api
    before: |
      echo "Setting up, please wait!"
      cd /workspace/bootcamp-fullstack-apps-with-cassandra 
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config 
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config 
      sdk install java 21.2.0.r11-grl -y
      pip3 install cassandra-driver
      npm install cassandra-driver
      wget https://downloads.datastax.com/enterprise/cqlsh-astra.tar.gz \
          && tar xvzf cqlsh-astra.tar.gz \
          && rm -f cqlsh-astra.tar.gz
      cp ~/.zshrc ~/.zshrc.init
      if [ -f /workspace/bootcamp-fullstack-apps-with-cassandra/zshrcinit ]; then
          cp /workspace/bootcamp-fullstack-apps-with-cassandra/zshrcinit ~/.zshrc
      fi
      pip3 install -r week4-api-microservices/python/requirements.txt
      npm i --prefix week4-api-microservices/javascript
ports:
  - port: 5005
  - port: 8080
    visibility: public
  - port: 8081
    onOpen: open-browser
  - port: 9191
    visibility: public
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - datastax.astra-for-vs-code
